#!/usr/bin/env bash

# install nginx web server
sudo apt-get update && sudo apt-get install nginx

# Start nginx service
sudo service nginx start

# create a file index.html with the string 'Hello World!'
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee  /var/www/html/index.html

# Restart nginx to apply the changes
sudo service nginx restart
