#!/usr/bin/env bash
# A script for installing nginx web server and update it with redirection

# install nginx web server
sudo apt-get update
apt-get -y install nginx

# Start nginx service 
sudo service nginx start

# Change the ownership of /var/www/html
sudo chown -R $USER:$USER /var/www/html

# Update the html doc
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Update nginx configuration to add redirection
sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default

# Test nginx configuration for syntax errors
sudo nginx -t

# Restart your nginx web server to apply the changes
sudo service nginx reload
