#!/usr/bin/env bash
# Install and configure nginx on web server

redirect_rule=$(cat <<EOF
    location /redirect_me {
        return 301 https://alvin05.hashnode.dev/what-happens-when-you-type-googlecom-in-your-browser-and-press-enter;
    }
EOF
)

sudo apt-get update
sudo apt-get -y install nginx # Install nginx

# Change file ownership
sudo chown -R "$USER":"$USER" /var/www/html

# Update HTML doc
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Shellcheck disable=SC1003
sudo sed -i -e "/^server {/,/^}/{/^}/i\\$redirect_rule" /etc/nginx/sites-available/default

# Check for configuration errors
sudo nginx -t

# Restart nginx
sudo service nginx reload
