#!/usr/bin/env bash
# install and configure nginx on web server

redirect_rule="\tlocation /redirect_me {\n\t\treturn 301 http://new-destination.com;\n\t}"

sudo apt-get update
sudo apt-get -y install nginx # install nginx

# change file owner
sudo chown -R "$USER":"$USER" /var/www/html

# update html doc
echo "Hello World!"  > /var/www/html/index.nginx-debian.html
# shellcheck disable=SC1003
sudo sed -i -e '/^server {/,/^}/{/^}/i\'"$redirect_rule" -e '}' /etc/nginx/sites-available/default

# check for configuration errors
sudo nginx -t
#restart nginx
sudo service nginx reload
