#!/usr/bin/env bash
# A script for installing nginx web server and update it with redirection and congigure it to use custom error page

# install nginx web server
sudo apt-get update && apt-get install nginx

# Start nginx service 
sudo service nginx start

# Create index.html with the string 'Hello World'
sudo touch index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Update nginx configuration to add redirection
sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default

# Create 404.html with the string 'Ceci n'est pas une page'
sudo touch 404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#Update nginx configuration to use custom error page 404
sudo sed -i '/^}$/i \ \n\terror_page 404 /404.html;\n\n\tlocation /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Test nginx configuration for syntax errors
sudo nginx -t

# Restart your nginx web server to apply the changes
sudo service nginx reload
