#!/usr/bin/env bash

# Group visitors by IP and HTTP status code, and count occurrences
awk '{ ip_code_count[$1" "$9]++ } END { for (pair in ip_code_count) print ip_code_count[pair], pair }' apache-access.log |
# Sort data by the number of occurrences in descending order
sort -nr |
# Format and display the data
awk '{ print $1, $2, $3 }'

