#!/usr/bin/env bash
# This script checks if a file named school exists
file="school"
#check if school file exists
if [ -e "$file" ];then
	echo "school file exists"
	#check if the file is empty
	if [ -s "$file" ];then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$file" ];then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
